# Site settings
title: Marenzio Online Digital Edition
email: lxpugin@gmailcom
baseurl: "" 
url: "http://www.marenzio.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: [src, varia]

groups:
    - name: "Books for four voices"
      books:
        - id: "M-01-4.xhtml"
          name: "Book I"
    - name: "Books for five voices"
      books:
        - id: "M-01-5.xhtml"
          name: "Book I"
        - id: "M-06-5.xhtml"
          name: "Book VI"
    - name: "Books for six voices"
      books:
        - id: "M-04-6.xhtml"
          name: "Book IV"

menu:
    - id: "about"
      name: "About MODE"
      submenu:
          - id: "acknowledgements"
            name: "Further acknowledgments"
          - id: "neh-grant"
            name: "NEH Grant"
          - id: "contact"
            name:  "Contact us"
    - id: "editorial-criteria"
      name: "Editorial criteria"
      submenu:
          - id: "editorial-criteria-music"
            name: "Music"
            url: "http://www.rism.info"
            blank: true
          - id: "editorial-criteria-text"
            name: "Poetic texts"
            url: "http://www.rism.info"
            blank: true
    - id: "catalogue"
      name: "Catalogue"
    - id: "links"
      name: "Links"
