# Site settings
title: Marenzio Online Digital Edition
email: lxpugin@gmailcom
baseurl: "/" 
url: "http://www.marenzio.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: [src, scripts, varia]

groups:
    - name: "Books for four voices"
      books:
        - id: "M-01-4.xhtml"
          name: "Book I"
    - name: "Books for five voices"
      books:
        - id: "M-01-5.xhtml"
          name: "Book I"
        - id: "M-06-5.xhtml"
          name: "Book VI"
    - name: "Books for six voices"
      books:
        - id: "M-04-6.xhtml"
          name: "Book IV"

menu:
    - id: "about"
      name: "About MODE"
      submenu:
          - id: "neh-grant"
            name: "NEH Grant"
          - id: "acknowledgments"
            name: "Further acknowledgments"
          - id: "contact"
            name:  "Contact us"
    - id: "editorial-criteria"
      name: "Editorial criteria"
      submenu:
          - id: "editorial-criteria-music"
            name: "Editorial criteria for the music (PDF)"
            url: "/pdfs/Mode_Criteria_Music.pdf"
            blank: true
          - id: "editorial-criteria-text"
            name: "Editorial criteria for the poetic texts (PDF)"
            url: "/pdfs/Mode_Criteria_Text.pdf"
            blank: true
    - id: "catalogue"
      name: "Catalogue"
      submenu:
          - id: "cecchi-marenzio-compositions"
            name: "Paolo Cecchi's list (PDF)"
            url: "/pdfs/Cecchi_Marenzio_Compositions.pdf"
            blank: true
    - id: "links"
      name: "Links"
